# Generated by Django 4.1.7 on 2024-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('age', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('price', models.FloatField(max_length=300, null=True)),
                ('category', models.DateTimeField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=300)),
            ],
        ),
    ]
